name: todo_ddc
description: Sample TODO app with polymer2+DDC
version: 0.0.1
dependencies:
 logging: any
 todo_main:
   path: todo_main
 polymer_element: "^0.3.0"
# polymer_elements:
#  git:
#    url: https://github.com/dam0vm3nt/polymerize_elements.git
#    ref: v0.1.0
# polymer_element: 
#   path: ../polymer_element
dependency_overrides:
# polymer_element:
#  path: /home/vittorio/Develop/dart/polymer_element
# polymer_elements:
#  path: /home/vittorio/Develop/dart/polymer_elements
 polymer_elements:
  git:
    url: https://github.com/dam0vm3nt/polymerize_elements.git
    ref: v0.1.7
